# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc2d85e498943097e6a53278cea6631f052c8ff56d24a5e1475f0a076c2c3d14212924ce9758ebd55883f5c2695332001524b60f9fdd90505ff7af5afda1f686

test:
  secret_key_base: 876a6f78ac45d53769c22c92523aabd5dab0c12d1857bb52598190064626dd18ce8a7e3598ece22bae47c74eb48469af8451cdfb33910000177899e82a842983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
